### ISSUE TITLE
WHDLoad_Booter.zip is missing

### ISSUE THREAD

**Issue by jakemelon** [HoraceAndTheSpider/RetroPieAmigaSetup#1]
# perform the download.
            data_source = "http://www.ultimateamiga.co.uk/HostedProjects/RetroPieAmiga/downloads/"
            data_file = "WHDLoad_Booter.zip"
            download_file(data_source + data_file,roms_folder + "amiga-data/WHDLoad_Booter.zip")

This file is no longer present at the above URL, hence the entire install/script fails. I was unable to find another copy of WHDLoad_Booter.zip anywhere. 

It could also be a permission issue....

**Comment by HoraceAndTheSpider** [comment]
Hi.
Please retry and confirm - just applied a fix to ftp which should resolve the.

**Comment by jakemelon** [comment]
Thank you!
