### ISSUE TITLE
Get rid of hard coded paths

### ISSUE THREAD

**Issue by bspinner** [HoraceAndTheSpider/RetroPieAmigaSetup#2]
Hey,

my RetroPie user is called `retropie` and not `pi`.
So I would appreciate an option to override the installation dir.

Unfortunately I'm neither fluent in Python, nor is the shell script mentioned in README in this repo.

btw: https://retropie.org.uk/forum/topic/14032/system-environment-variable-pointing-to-retropie-dir

**Comment by HoraceAndTheSpider** [comment]
hi @bspinner 

this shouldnt be too hard - I will need to add a command-line input variable for `base_folder = "/home/pi/RetroPie/"`  and that would fix it for you, since everything else cascades down from there.

**Comment by HoraceAndTheSpider** [comment]
I’ve probably sorted this - just need to test and will upload later

**Comment by HoraceAndTheSpider** [comment]
@bspinner 

I have used the suggested ~/RetroPie/ path, and updated the readme to accomodate. I have also added the fall-back of specifying the path from the command line (using --retropie-path= ) should you need it.

Please let me know if this is working for you.

**Comment by bspinner** [comment]
The scripts in this repo are working fine now.
Now `UAE Config Maker.sh` is misbehaving. Second line starts with `pushd /home/pi`. :)
And since no path parameters are given to `uae_config_maker.py`, the `/home/pi` defaults are used. 
So some steps are still to do for a cool out-of-the-box experience. :)

**Comment by bspinner** [comment]
Almost forgot the most important: huge thanks for the responsiveness!

**Comment by HoraceAndTheSpider** [comment]
`UAE Config Maker.sh` is (should have been) hosted via the UAE Config Maker project github, so if it's OK, i'll close this here and look into that seperately to achieve the same.

You can, of course, edit that one script manually and put the needed command line parameters into it.

Feel free to raise an issue on the other project seperately, which will be a bit slower updating i'm afraid, as there are quite a few changes needed there (waiting for amiberry updates to complete)
