### ISSUE TITLE
Files won't download

### ISSUE THREAD

**Issue by Th-reep** [HoraceAndTheSpider/RetroPieAmigaSetup#3]
Hi there! Thanks for this awesome tool! I tried to install whdload via your script. When I tried to install it from the retropie menu, though, it did not work. The script: 
_cd ~/RetroPie/retropiemenu/
rm "Auto-Amiga Install.sh"
wget https://raw.githubusercontent.com/HoraceAndTheSpider/RetroPieAmigaSetup/master/Auto-Amiga%20Install.sh
chmod +x "Auto-Amiga Install.sh"_ 
correctly addedd the install option in the retropie menu, but when I tried to install the actual package from the menu, every file it tried to download/install was "not found". What could it be? I will try the manual installation in case
thanks!

**Comment by HoraceAndTheSpider** [comment]
Hi

Try this script from my mirrored source. Possibly i have updated one not the other!

```
cd /home/pi/RetroPie/retropiemenu/
sudo rm "Auto-Amiga Install.sh"
sudo wget "http://www.djcresswell.com/amigaonline/HyperPie/Auto-Amiga Install.sh"
sudo chmod +x "Auto-Amiga Install.sh"
sudo ./"Auto-Amiga Install.sh"
```

**Comment by Th-reep** [comment]
Thanks a lot, I will try it ASAP!
________________________________
Da: Horace And The Spider <notifications@github.com>
Inviato: giovedì 1 febbraio 2018 13:53
A: HoraceAndTheSpider/RetroPieAmigaSetup
Cc: Th-reep; Author
Oggetto: Re: [HoraceAndTheSpider/RetroPieAmigaSetup] Files won't download (#3)


Hi

Try this script from my mirrored source. Possibly i have updated one not the other!

cd /home/pi/RetroPie/retropiemenu/
sudo rm "Auto-Amiga Install.sh"
sudo wget "http://www.djcresswell.com/amigaonline/HyperPie/Auto-Amiga Install.sh"
sudo chmod +x "Auto-Amiga Install.sh"
sudo ./"Auto-Amiga Install.sh"

**Comment by Th-reep** [comment]
It worked! thanks a lot, it would have been much more complicated to set it up manually
have a nice week,
D.
________________________________
Da: Horace And The Spider <notifications@github.com>
Inviato: giovedì 1 febbraio 2018 13:53
A: HoraceAndTheSpider/RetroPieAmigaSetup
Cc: Th-reep; Author
Oggetto: Re: [HoraceAndTheSpider/RetroPieAmigaSetup] Files won't download (#3)


Hi

Try this script from my mirrored source. Possibly i have updated one not the other!

cd /home/pi/RetroPie/retropiemenu/
sudo rm "Auto-Amiga Install.sh"
sudo wget "http://www.djcresswell.com/amigaonline/HyperPie/Auto-Amiga Install.sh"
sudo chmod +x "Auto-Amiga Install.sh"
sudo ./"Auto-Amiga Install.sh"

**Comment by HoraceAndTheSpider** [comment]
Good to know. I which check for differences and upload a fix.
